services:
  web:
    build: .
    volumes:
      - .:/code
      - db_data:/code/db
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    restart: unless-stopped

volumes:
  db_data: